labels:
  - name: "bug 🐛"
    labeled:
      issue:
        body: Thanks for reporting!
  - name: "feature ➕"
    labeled:
      issue:
        body: Thanks for the suggestion!
  - name: invalid-template
    labeled:
      issue:
        body: '@{{ issue.user.login }} Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.'
